### ISSUE TITLE
it won't install archetype in a new environment

### ISSUE THREAD

**Issue by yjlcoder** [snlab/Maple-release#1]
I install this in a new environment (Ubuntu 14.04), and there are some errors because of the absence of archetype.

Please uncomment the code of archetype process and update snlab/maple-archetype to follow the latest release.

Thank you.

**Comment by fno2010** [comment]
@LovingYoung @yutao33 What's the current state of this issue? I tested the latest pre-release binary and installer. There is no issue. Is it an immediate issue? Or it has been fixed?

**Comment by yjlcoder** [comment]
@fno2010 There is so such an issue. I just made a mistake to setup the environment. Thank you anyway.
